internalGrpcPort: 8082

global:
  auth:
    dexServerAddr:

cache:
  syncInterval: 10s
  userManagerServerInternalAddr: user-manager-server-internal-grpc:8082
  clusterManagerServerInternalAddr: cluster-manager-server-internal-grpc:8083

roleScopesMap:
  organizationOwner:
  - api.model.read
  - api.model.write
  - api.fine_tuning.jobs.read
  - api.fine_tuning.jobs.write
  - api.workspaces.notebooks.read
  - api.workspaces.notebooks.write
  - api.batch.jobs.read
  - api.batch.jobs.write
  - api.files.read
  - api.files.write
  - api.vector-stores.read
  - api.vector-stores.write
  - api.clusters.read
  - api.clusters.write
  projectOwner:
  - api.model.read
  - api.model.write
  - api.fine_tuning.jobs.read
  - api.fine_tuning.jobs.write
  - api.workspaces.notebooks.read
  - api.workspaces.notebooks.write
  - api.batch.jobs.read
  - api.batch.jobs.write
  - api.files.read
  - api.files.write
  - api.vector-stores.read
  - api.vector-stores.write
  projectMember:
  - api.model.read
  - api.model.write
  - api.fine_tuning.jobs.read
  - api.fine_tuning.jobs.write
  - api.workspaces.notebooks.read
  - api.workspaces.notebooks.write
  - api.batch.jobs.read
  - api.batch.jobs.write
  - api.files.read
  - api.files.write
  - api.vector-stores.read
  - api.vector-stores.write

debug:
  apiKeyRole: projectMember

replicaCount: 1

image:
  repository: public.ecr.aws/cloudnatix/llm-operator/rbac-server
  pullPolicy: IfNotPresent

podAnnotations:
nodeSelector:
affinity:
tolerations:

version:

resources:
  requests:
    cpu: "250m"
    memory: "500Mi"
  limits:
    cpu: "250m"

livenessProbe:
  grpc:
    port: 8082
  initialDelaySeconds: 3
  failureThreshold: 5

podSecurityContext:
  fsGroup: 2000
securityContext:
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
