global:
  auth:
    oidcIssuerUrl:

internalGrpcPort: 8082

cache:
  syncInterval: 10s
  userManagerServerInternalAddr: user-manager-server-internal-grpc:8082
  clusterManagerServerInternalAddr: cluster-manager-server-internal-grpc:8083

roleScopesMap:
  organizationOwner:
  - api.model.read
  - api.model.write
  - api.fine_tuning.jobs.read
  - api.fine_tuning.jobs.write
  - api.workspaces.notebooks.read
  - api.workspaces.notebooks.write
  - api.files.read
  - api.files.write
  - api.vector-stores.read
  - api.vector-stores.write
  - api.clusters.read
  - api.clusters.write
  projectOwner:
  - api.model.read
  - api.model.write
  - api.fine_tuning.jobs.read
  - api.fine_tuning.jobs.write
  - api.workspaces.notebooks.read
  - api.workspaces.notebooks.write
  - api.files.read
  - api.files.write
  - api.vector-stores.read
  - api.vector-stores.write
  projectMember:
  - api.model.read
  - api.model.write
  - api.fine_tuning.jobs.read
  - api.fine_tuning.jobs.write
  - api.workspaces.notebooks.read
  - api.workspaces.notebooks.write
  - api.files.read
  - api.files.write
  - api.vector-stores.read
  - api.vector-stores.write

debug:
  apiKeyRole: projectMember

replicaCount: 1

image:
  repository: public.ecr.aws/cloudnatix/llm-operator/rbac-server
  pullPolicy: IfNotPresent

version:
