global:
  auth:
    oidcIssuerUrl:

internalGrpcPort: 8082

cache:
  syncInterval: 10s
  userManagerServerInternalAddr: user-manager-server-internal-grpc:8082

roleScopesMap:
  organizationOwner:
  - api.model.read
  - api.model.write
  - api.fine_tuning.jobs.read
  - api.fine_tuning.jobs.write
  - api.files.read
  - api.files.write
  - api.users.api_keys.read
  - api.users.api_keys.write
  projectOwner:
  - api.model.read
  - api.model.write
  - api.fine_tuning.jobs.read
  - api.fine_tuning.jobs.write
  - api.files.read
  - api.files.write
  - api.users.api_keys.read
  - api.users.api_keys.write
  projectMember:
  - api.model.read
  - api.model.write
  - api.fine_tuning.jobs.read
  - api.fine_tuning.jobs.write
  - api.files.read
  - api.files.write
  - api.users.api_keys.read
  - api.users.api_keys.write


debug:
  apiKeyRole: projectMember

replicaCount: 1

image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/rbac-server
  pullPolicy: IfNotPresent

version:
