apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dex-server.fullname" . }}
  labels:
    {{- include "dex-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    issuer: {{ .Values.global.auth.oidcIssuerUrl }}
    storage:
      type: postgres
      config:
        host: {{ .Values.global.database.host }}
        port: {{ .Values.global.database.port }}
        database: {{ .Values.database.database }}
        user: {{ .Values.global.database.username }}
        password: $PASSWORD_ENV_VAR
        ssl:
          mode: {{ .Values.global.database.ssl.mode }}

    web:
      http: 0.0.0.0:{{ .Values.httpPort }}
    grpc:
      addr: 0.0.0.0:{{ .Values.internalGrpcPort }}

    oauth2:
      skipApprovalScreen: true
      {{- with .Values.oauth2.passwordConnector }}
      {{- if .enable }}
      passwordConnector: {{ .value}}
      {{- end }}
      {{- end }}
      responseTypes: {{ .Values.oauth2.responseTypes }}
      alwaysShowLoginScreen: false

    connectors:
    {{- toYaml .Values.connectors | nindent 4 }}

    {{- with .Values.staticClient }}
    {{- if .enable }}
    staticClients:
    - id: {{ .id }}
      redirectURIs:
      - {{ .redirectUrl }}
      name: {{ .name }}
      secret: {{ .secret }}
    {{- end }}
    {{- end }}

    enablePasswordDB: {{ .Values.enablePasswordDb }}

    {{- with .Values.staticPassword }}
    {{- if .enable }}
    staticPasswords:
    - userID: {{ .id }}
      username: {{ .name }}
      email: {{ .email }}
      hash: {{ .password }}
    {{- end }}
    {{- end }}
