apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dex-server.fullname" . }}
  labels:
    {{- include "dex-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dex-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dex-server.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ sha256sum (toJson .Values) }}
    spec:
      containers:
      - name: dex
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - dex
        - serve
        - /etc/config/config.yaml
        ports:
        - name: http
          containerPort: {{ .Values.httpPort }}
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: {{ include "dex-server.fullname" . }}
