apiVersion: v1
kind: Service
metadata:
  name: {{ include "dex-server.fullname" . }}-http
  labels:
    {{- include "dex-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.httpPort }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "dex-server.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dex-server.fullname" . }}-internal-grpc
  labels:
    {{- include "dex-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.internalGrpcPort }}
    targetPort: internal-grpc
    protocol: TCP
    name: internal-grpc
  selector:
    {{- include "dex-server.selectorLabels" . | nindent 4 }}
