apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rbac-server.fullname" . }}
  labels:
    {{- include "rbac-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    internalGrpcPort: {{ .Values.internalGrpcPort }}
    issuerUrl: {{ .Values.global.auth.oidcIssuerUrl }}
    cache:
      syncInterval: {{ .Values.cache.syncInterval }}
      userManagerServerInternalAddr: {{ .Values.cache.userManagerServerInternalAddr }}
      clusterManagerServerInternalAddr: {{ .Values.cache.clusterManagerServerInternalAddr }}
    roleScopesMap:
      {{- toYaml .Values.roleScopesMap | nindent 6 }}
    debug:
      {{- toYaml .Values.debug | nindent 6 }}
