apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rbac-server.fullname" . }}
  labels:
    {{- include "rbac-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    internalGrpcPort: {{ .Values.internalGrpcPort }}
    issuerUrl: {{ .Values.issuerUrl }}
    debug:
      {{- toYaml .Values.debug | nindent 6 }}
