name: CI-post-merge
on:
  push:
    branches:
    - main

permissions:
  # This is necessary for AWS credentials. See:
  # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings
  id-token: write
  contents: write

jobs:

  update-tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
    - uses: actions/checkout@v4
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor

  publish-helm-chart:
    runs-on: ubuntu-latest
    needs:
    - update-tag
    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::803339316953:role/github-actions-ecr-push-llm-operators
        aws-region: us-west-2
    - name: Set up Helm
      uses: Azure/setup-helm@v4
    - name: Set up charts directory
      run: mkdir charts
    - name: build dex helm chart
      run: helm package --version ${{ needs.update-tag.outputs.new_tag }} --destination ./charts ./deployments/dex-server
    - name: Rebuild index.yaml and push
      run: |
        curl -o index.yaml http://llm-operator-charts.s3-website-us-west-2.amazonaws.com/index.yaml
        helm repo index charts --merge index.yaml --url http://llm-operator-charts.s3-website-us-west-2.amazonaws.com/
        aws s3 sync ./charts s3://llm-operator-charts
